### ISSUE TITLE
Publicize this repo as an #awesome list!

### ISSUE THREAD

**Issue by srudolph-credera** [jmatthiesen/dotnet-ai-resources#4]
This is a great curated collection! Have you considered adding the #awesome topic (https://github.com/topics/awesome) and requesting official status as an awesome list? See: https://github.com/sindresorhus/awesome/blob/main/awesome.md.

**Comment by jmatthiesen** [comment]
Thanks for sharing, I didn't release there was a way to publish an official list!

**Comment by jmatthiesen** [comment]
Done - Thanks!
